### ISSUE TITLE
Host on GH Pages

### ISSUE THREAD

**Issue by akrigline** [League-of-Foundry-Developers/FoundryGet-PackageBrowser#1]
Is this project one that could be hosted on GH Pages? 

A quick search shows that there doesn't seem to be any major hurdles to deploying a Vue app to GH Pages. It would be neat to be able to browse this package browser in a hosted environment.

**Comment by ardittristan** [comment]
That was my original intent, I don't know if everyone else also agrees with it. But I want to have it at least work as page. Maybe with some features disabled if they don't work.

**Comment by akrigline** [comment]
This appears to be [working](https://league-of-foundry-developers.github.io/FoundryGet-PackageBrowser/).
